export const carModels = [
  "Lada Vesta",
  "Lada Granta",
  "Lada Niva Travel",
  "Lada Niva Legend",
  "Lada XRAY",
  "Lada Largus",
  "Kia Rio",
  "Kia Rio X",
  "Kia K5",
  "Kia Ceed",
  "Kia Sportage",
  "Kia Sorento",
  "Kia Soul",
  "Hyundai Solaris",
  "Hyundai Creta",
  "Hyundai Elantra",
  "Hyundai Tucson",
  "Hyundai Santa Fe",
  "Hyundai Accent",
  "Toyota Camry",
  "Toyota Corolla",
  "Toyota RAV4",
  "Toyota Land Cruiser",
  "Toyota Land Cruiser Prado",
  "Toyota Highlander",
  "Volkswagen Polo",
  "Volkswagen Tiguan",
  "Volkswagen Passat",
  "Volkswagen Jetta",
  "Renault Logan",
  "Renault Sandero",
  "Renault Duster",
  "Renault Arkana",
  "Renault Kaptur",
  "Skoda Rapid",
  "Skoda Octavia",
  "Skoda Kodiaq",
  "Skoda Karoq",
  "Nissan Almera",
  "Nissan Qashqai",
  "Nissan X-Trail",
  "Nissan Terrano",
  "Chevrolet Niva",
  "Chevrolet Aveo",
  "Chevrolet Cobalt",
  "Datsun on-DO",
  "Datsun mi-DO",
  "Geely Coolray",
  "Geely Atlas",
  "Geely Monjaro",
  "Geely Emgrand",
  "Chery Tiggo 4",
  "Chery Tiggo 7",
  "Chery Tiggo 8",
  "Chery Arrizo",
  "Haval Jolion",
  "Haval F7",
  "Haval M6",
  "Haval Dargo",
  "UAZ Patriot",
  "UAZ Hunter",
  "UAZ Profi",
  "ГАЗ Газель Next",
  "ГАЗ Газель Business",
  "ГАЗ Соболь",
  "Mazda 3",
  "Mazda 6",
  "Mazda CX-5",
  "Ford Focus",
  "Ford EcoSport",
  "Ford Mondeo",
  "Honda CR-V",
  "Honda Civic",
  "Honda Accord",
  "Mitsubishi Outlander",
  "Mitsubishi ASX",
  "Mitsubishi Pajero",
  "BMW 3 серии",
  "BMW 5 серии",
  "BMW X5",
  "Mercedes-Benz E-Класс",
  "Mercedes-Benz C-Класс",
  "Mercedes-Benz Sprinter",
  "Audi A4",
  "Audi A6",
  "Audi Q5",
  "Peugeot 408",
  "Peugeot 3008",
  "Citroen C4",
  "Citroen Berlingo",
  "Opel Astra",
  "Opel Corsa",
  "Subaru Forester",
  "Subaru Outback",
  "Suzuki Vitara",
  "Suzuki SX4",
  "Changan CS35 Plus",
  "Changan CS55",
  "Changan Alsvin",
  "Exeed TXL",
  "Exeed LX",
  "FAW Bestune T77",
];
